# If taking Docker Mastery, this is the same file you created in 
# ./compose-assignment-2
# If taking Swarm Mastery, this is your starting point for adding secrets :)
# reminder, this needs to change to 3.1 version to use secrets!
version: '3.1'

services:

  drupal:
    image: drupal:8.5.4
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
    networks:
      - drupal
    depends_on:
      - postgres
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
 
  postgres:
    image: postgres:10.4
    secrets:
      - psql_user
      - psql_passwd    
    environment:
      POSTGRES_PASSWORD: 'mydbpass'
      POSTGRES_USER: 'postgres'
    volumes:
      - drupal-data:/var/lib/postgresql/data
    networks:
      - drupal
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure      

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

secrets:
  psql_user:
    external: true
  psql_passwd:
    external: true

networks:
  drupal: